config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'
  devise_for :users

  get "messages/index2" => "messages#index2"
  resources :rooms, only: [:new, :create, :index, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms, validate: false
  has_many :messages, dependent: :destroy

  validates :room_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :user_rooms
    has_many :rooms, through: :user_rooms
    has_many :messages
         
    validates :name, presence: true
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
     
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user! 
  
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def index2
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:message).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to messages_index2_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to messages_index2_path
    end

  private

  def room_params
    params.require(:room).permit(:room_name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def edit
end

def update
  if current_user.update(user_params)
    redirect_to root_path
  else
    render :edit
  end
end

def show
  @user = User.find(params[:id])
end

private

def user_params
  params.require(:user).permit(:name, :email, :password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messagse_helper.rb
module MessagseHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rindoku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", media: "all" %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.room_name%>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to '輪読を終了する', room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model:[@room, @message], class: 'form', local:true do |f|%>
  <div class="form-input">
    <%= f.text_field :message, class: 'form-message', placeholder: 'メッセージを入力してください' %>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= link_to message.user.name, user_path(message.user.id)%>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.message%>
    </div>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="user-name">
    <%= link_to current_user.name, user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to 'グループを作成する', new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.room_name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/messages/index2.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
  

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <div class='title-contents'>
    <h2 class='service-title'>
      一歩先の読書体験を
    </h2>
    <p class='service-explain'>
      Rindokuで気軽にオンライン輪読会
    </p>
  </div>

  <div class='select-reason-contents'>
    <h2 class='title'>
      ただの読書ではなく、その先へ
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "pic.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>より深い読書</span>
          
        </h3>
        <p class='reason-list-description'>
          他者の視点にふれて、視野が広がる
        </p>
      </li>
      <li class='list'>
        <%= image_tag "pic2.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>より効率的な読書</span>
          
        </h3>
        <p class='reason-list-description'>
          グループで分担して読むことで、効率的に理解する
        </p>
      </li>
      <li class='list'>
      <%= image_tag "pic3.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>アウトプットの場</span>
        </h3>
        <p class='reason-list-description'>
        知識をアウトプットすることで、知識を力に変える
        </p>
      </li>
    </ul>
  </div>

  <div class='ad-contents'>
    <h2 class='ad-title'>
      <span>Rindoku</span>で人生を変えよう。
    </h2>
    <p class='ad-explain'>
      読書はしているけれど、なかなか力にならないと思っているあなたへ。
    </p>
    <p class='ad-explain'>
      Rindokuで学びを成長につなげましょう。
    </p>
    <p class='ad-explain'>
      インプット重視からアウトプット重視の読書へ。
    </p>
    
  </div>

  <div class='feature-contents'>
    <h2 class='title'>
      Rindokuの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <h3 class='feature-list-text'>
          かんたんに始められる！
        </h3>
        <p class='feature-list-description'>
          面倒な申込みは必要ありません。
        </p>
      </li>
      <li class='list'>
        <h3 class='feature-list-text'>
          わずらわしい通知なし！
        </h3>
        <p class='feature-list-description'>
          その他SNS等とアプリを分けることで、通知がごちゃごちゃになりません。
        </p>
      </li>
      <li class='list'>
        <h3 class='feature-list-text'>
          スキマ時間で学べる！
        </h3>
        <p class='feature-list-description'>
          チャット形式のメッセージ投稿なので、スキマ時間に学べる
        </p>
      </li>
    </ul>
  </div>
 

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>グループを作成！</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :グループ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :room_name, class: 'chat__room_name chat-room-form__input', placeholder: 'グループ名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>輪読メンバー</label>
        <p>※複数メンバー選択時は<br>shiftキーを押しながらメンバーを選択してください。</p>
      </div>
      <div class='chat-room-form__field--right'>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/i18n/ja.js"></script>
          <select name="room[user_ids][]" class="user-select2"  multiple="multiple">
            <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
          </select>
          <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
      <ul class = 'session'>
      <% if user_signed_in? %>
       <li>
       <%= "こんにちは、" %>
       <%= link_to current_user.name, user_path(current_user), class: "user-name" %>
       <%= "さん" %>
        </li> 
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"  %> </li>
        <ul class = 'header-right'>
          <li><%= link_to '新規グループを作成する', new_room_path, class: "new-group"%>
          <li><%= link_to 'メッセージ一覧を見る', messages_index2_path, class: "new-group"%>
       
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      </ul>
  </div>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <h5>※情報編集後は再度ログインしてください。</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
          <div class="field">
            <div class='field-label'>
              <%= f.label :new_password %> 
            </div>
            <div class='field-input'>
              <%= f.password_field :password %>
            </div>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p>MyPage <%= @user.name %></p>